language: java
# Disable email notification
notifications:
  email: false
  
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      
# Enable sudo
sudo: true
# Build command
script: "travis_wait mvn clean -DskipTests=false verify"
