language: java
# Enable caching
cache: bundler
# Build command
script: "mvn -DskipTests=false jfx:jar"

sudo:true

matrix:
    include:
        - jdk: oraclejdk8
        addons:
          apt:
            packages:
              - oracle-java8-installer
